name: Release

on:
  push:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: 2
          token: ${{ secrets.PAT_TOKEN }}

      - name: Check diff (files)
        id: version-check
        run: |
          if [[ "$(git diff HEAD~1..HEAD --unified=0 Cargo.toml)" = *"version"* ]]; then
            echo "::set-output name=ver::$(cat Cargo.toml | grep "version" | head -n 1 | sed -E 's/^.*"(.+)".*$/\1/')"
          else
            echo "::set-output name=ver::---"
          fi

      - name: Create and push tag
        if: ${{ steps.version-check.outputs.ver != '---' }}
        run: |
          git config user.name loxygenK
          git config user.email me@loxygen.dev
          git tags ${{ steps.version-check.outputs.ver }}
          git push origin --tags

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.version-check.outputs.ver != '---' }}
        with:
          tag_name: ${{ steps.version-check.outputs.ver }}
          token: ${{ secrets.PAT_TOKEN }}

      # - name: Push to Cargo
      #   run: |
      #     cargo publish
      #   env:
      #     CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
