name: Test with coverage

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Test and generate coverage
        run: cargo tarpaulin --verbose --timeout 120 --out Xml

      - name: Upload the coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
